using System.Collections.Generic;
using Godot.BindingsGeneration.ApiDump;
using Godot.BindingsGeneration.Reflection;
using Godot.BindingsGeneration.Logging;

namespace Godot.BindingsGeneration;

internal sealed partial class BindingsData
{
    public GodotApiHeader Header { get; }

    private readonly TypeDB _typeDB = new();

    private readonly XmlDocConverter _xmlDocConverter;

    /// <summary>
    /// Collection of C# type information that was created from <see cref="GodotApi"/>.
    /// This type information will be used to generate C# types.
    /// </summary>
    public IReadOnlyCollection<GeneratedTypeData> Types => _generatedTypesByPath.Values;

    /// <summary>
    /// Collection of C# type information for tests that was created from <see cref="GodotApi"/>.
    /// This type information will be used to generate C# test types.
    /// </summary>
    public IReadOnlyCollection<GeneratedTypeData> TestTypes => _generatedTestTypesByPath.Values;

    // Stores the types that will be generated.
    private readonly HashSet<TypeInfo> _generatedTypes = [];

    // Stores the types that will be generated so they can be retrieved by their path.
    private readonly Dictionary<string, GeneratedTypeData> _generatedTypesByPath = [];

    private readonly Dictionary<string, GeneratedTypeData> _generatedTestTypesByPath = [];

    // Stores the inline arrays that will be generated by their length.
    private readonly Dictionary<int, TypeInfo> _inlineArrays = [];

    // Stores the singleton information by the engine name of the type that is marked as singleton.
    private readonly Dictionary<string, GodotSingletonInfo> _singletons = [];

    private readonly BindingsDataCollector[] _dataCollectors =
    [
        new GlobalConstantsBindingsDataCollector(),
        new BuiltInClassesBindingsDataCollector(),
        new EngineClassesBindingsDataCollector(),
        new NativeStructuresBindingsDataCollector(),
        new GlobalEnumsBindingsDataCollector(),
        new UtilityFunctionsBindingsDataCollector(),
        new VariadicGenericsBindingsDataCollector(),
    ];

    private BindingsData(GodotApiHeader header)
    {
        Header = header;
        RegisterKnownTypes();

        _xmlDocConverter = new XmlDocConverter(_typeDB);
    }

    /// <summary>
    /// Constructs a <see cref="BindingsData"/> instance and populate it with the
    /// necessary information from the given <paramref name="api"/> to generate
    /// the C# bindings for the engine core API.
    /// </summary>
    /// <param name="api">API information deserialized from the JSON dump.</param>
    /// <param name="options">Options that configure the bindings generation.</param>
    /// <param name="logger">Logger that logs information messages, warnings, and errors.</param>
    /// <returns>A populated instance of <see cref="BindingsData"/>.</returns>
    internal static BindingsData CreateForCore(GodotApi api, BindingsGeneratorOptions options, ILogger? logger = null)
    {
        logger ??= ConsoleLogger.Instance;

        var data = new BindingsData(api.Header);

        var context = new CollectionContext(data, api, options, logger);

        // First create all the TypeInfo instances, then populate them as a second step
        // so we can retrieve references to other TypeInfo instances when populating.
        data.InitializeTypes(context);
        data.PopulateTypes(context);

        return data;
    }

    /// <summary>
    /// Constructs a <see cref="BindingsData"/> instance and populate it with the
    /// necessary information from the given <paramref name="coreApi"/> and
    /// <paramref name="extensionApi"/> to generate the C# bindings for the extension API.
    /// </summary>
    /// <param name="coreApi">API information deserialized from the JSON dump for the engine core API.</param>
    /// <param name="extensionApi">API information deserialized from the JSON dump for the extension.</param>
    /// <param name="options">Options that configure the bindings generation.</param>
    /// <param name="logger">Logger that logs information messages, warnings, and errors.</param>
    /// <returns>A populated instance of <see cref="BindingsData"/>.</returns>
    internal static BindingsData CreateForGDExtension(GodotApi coreApi, GodotApi extensionApi, BindingsGeneratorOptions options, ILogger? logger = null)
    {
        logger ??= ConsoleLogger.Instance;

        // First populate the data with the core API so the extension API
        // can reference the generated types from the core API.
        var data = CreateForCore(coreApi, new BindingsGeneratorOptions(), NullLogger.Instance);

        // Clear the generated types added for the core API, since we'll only
        // generate the extension API types.
        data._generatedTypes.Clear();
        data._generatedTypesByPath.Clear();
        data._generatedTestTypesByPath.Clear();

        var context = new CollectionContext(data, extensionApi, options, logger)
        {
            IsExtension = true,
        };

        // First create all the TypeInfo instances, then populate them as a second step
        // so we can retrieve references to other TypeInfo instances when populating.
        data.InitializeTypes(context);
        data.PopulateTypes(context);

        return data;
    }

    private void InitializeTypes(CollectionContext context)
    {
        foreach (var collector in _dataCollectors)
        {
            collector.Initialize(context);
        }

        RegisterSingletons(context.Api);
    }

    private void PopulateTypes(CollectionContext context)
    {
        foreach (var collector in _dataCollectors)
        {
            collector.Populate(context);
        }

        // Now that all types have been initialized and populated, we can convert the documentation
        // from BBCode to XMLDoc format. Documentation may reference other types and members, so
        // we need to wait until all types are populated to ensure all references can be resolved.
        if (context.Options.IncludeDocumentation)
        {
            ConvertDocumentation();
        }
    }

    private void RegisterSingletons(GodotApi api)
    {
        foreach (var engineSingleton in api.Singletons)
        {
            _singletons[engineSingleton.Type] = engineSingleton;
        }
    }

    private void ConvertDocumentation()
    {
        foreach (var type in _generatedTypes)
        {
            ConvertDocumentationForType(type, _xmlDocConverter);
        }

        static void ConvertDocumentationForType(TypeInfo type, XmlDocConverter converter)
        {
            TypeInfo? currentType = type;
            if (type.IsEnum)
            {
                // For enums we want to use the containing type as the current type when converting documentation
                // because enum members reference other members relative to the containing type.
                currentType = type.ContainingType;
            }

            if (!string.IsNullOrEmpty(type.Documentation))
            {
                type.Documentation = converter.Convert(type.Documentation, currentType);
            }

            foreach (var nestedType in type.NestedTypes)
            {
                ConvertDocumentationForType(nestedType, converter);
            }

            foreach (var constructor in type.DeclaredConstructors)
            {
                if (!string.IsNullOrEmpty(constructor.Documentation))
                {
                    constructor.Documentation = converter.Convert(constructor.Documentation, currentType);
                }
            }

            foreach (var method in type.DeclaredMethods)
            {
                if (!string.IsNullOrEmpty(method.Documentation))
                {
                    method.Documentation = converter.Convert(method.Documentation, currentType);
                }
            }

            foreach (var property in type.DeclaredProperties)
            {
                if (!string.IsNullOrEmpty(property.Documentation))
                {
                    property.Documentation = converter.Convert(property.Documentation, currentType);
                }
            }

            foreach (var field in type.DeclaredFields)
            {
                if (!string.IsNullOrEmpty(field.Documentation))
                {
                    field.Documentation = converter.Convert(field.Documentation, currentType);
                }
            }

            foreach (var @event in type.DeclaredEvents)
            {
                if (!string.IsNullOrEmpty(@event.Documentation))
                {
                    @event.Documentation = converter.Convert(@event.Documentation, currentType);
                }
            }
        }
    }
}
