using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Linq;
using Godot.BindingsGeneration.ApiDump;
using Godot.BindingsGeneration.Reflection;
using Godot.BindingsGeneration.Logging;

namespace Godot.BindingsGeneration;

/// <summary>
/// Provides methods for generating bindings for the Godot engine and GDExtensions.
/// </summary>
public static partial class BindingsGenerator
{
    /// <summary>
    /// Generate bindings for the Godot core engine API.
    /// </summary>
    /// <param name="api">The core engine API to generate bindings for.</param>
    /// <param name="writerFactory">The factory to create writers for the generated bindings.</param>
    /// <param name="options">Options for configuring the behavior of the bindings generator.</param>
    /// <param name="logger">The logger to use for logging messages during generation.</param>
    public static void GenerateEngineBindings(GodotApi api, IBindingsGeneratorWriterFactory writerFactory, BindingsGeneratorOptions? options = null, ILogger? logger = null)
    {
        options ??= new();
        logger ??= ConsoleLogger.Instance;

        if (!ValidateOptionsForGeneration(api, options, logger))
        {
            return;
        }

        if (options.Namespace != "Godot")
        {
            logger.LogError("Godot engine bindings must use the 'Godot' namespace.");
            return;
        }

        var data = BindingsData.CreateForCore(api, options, logger);
        GenerateCore(data, writerFactory, logger);
    }

    /// <summary>
    /// Generate bindings for a GDExtension API.
    /// </summary>
    /// <param name="coreApi">The core engine API to use as reference for the GDExtension API.</param>
    /// <param name="extensionApi">The GDExtension API to generate bindings for.</param>
    /// <param name="writerFactory">The factory to create writers for the generated bindings.</param>
    /// <param name="options">Options for configuring the behavior of the bindings generator.</param>
    /// <param name="logger">The logger to use for logging messages during generation.</param>
    public static void GenerateGDExtensionBindings(GodotApi coreApi, GodotApi extensionApi, IBindingsGeneratorWriterFactory writerFactory, BindingsGeneratorOptions? options = null, ILogger? logger = null)
    {
        options ??= new();
        logger ??= ConsoleLogger.Instance;

        if (!ValidateOptionsForGenerationAgainstCore(coreApi, options, logger))
        {
            return;
        }

        if (!ValidateOptionsForGeneration(extensionApi, options, logger))
        {
            return;
        }

        if (options.Namespace == "Godot")
        {
            logger.LogError("GDExtension bindings must not use the 'Godot' namespace.");
            return;
        }

        var data = BindingsData.CreateForGDExtension(coreApi, extensionApi, options, logger);
        GenerateCore(data, writerFactory, logger);
    }

    private static bool ValidateOptionsForGeneration(GodotApi api, BindingsGeneratorOptions options, ILogger logger)
    {
        // Validate that the requested precision matches the API.
        var apiPrecision = api.Header.Precision;
        var optionsPrecision = (GodotFloatTypePrecision)options.FloatPrecision;
        if (apiPrecision != optionsPrecision)
        {
            logger.LogError($"Cannot build for precision '{optionsPrecision}' using 'extension_api.json' which was generated by Godot built with precision '{apiPrecision}'.");
            return false;
        }

        return true;
    }

    private static bool ValidateOptionsForGenerationAgainstCore(GodotApi coreApi, BindingsGeneratorOptions options, ILogger logger)
    {
        // Validate that the requested precision matches the core API that is built into the generator.
        var apiPrecision = coreApi.Header.Precision;
        var optionsPrecision = (GodotFloatTypePrecision)options.FloatPrecision;
        if (apiPrecision != optionsPrecision)
        {
            logger.LogError($"Cannot generate GDExtension bindings for precision '{optionsPrecision}' using 'extension_api.json' which was generated by Godot built with precision '{apiPrecision}'.");
            return false;
        }

        return true;
    }

    private static void GenerateCore(BindingsData data, IBindingsGeneratorWriterFactory writerFactory, ILogger logger)
    {
        foreach (var generationData in data.Types)
        {
            ProcessType(writerFactory, generationData, isTestOutput: false, logger);
        }

        if (writerFactory.SupportsTestOutput)
        {
            foreach (var generationData in data.TestTypes)
            {
                ProcessType(writerFactory, generationData, isTestOutput: true, logger);
            }
        }

        static void ProcessType(IBindingsGeneratorWriterFactory writerFactory, GeneratedTypeData generationData, bool isTestOutput, ILogger logger)
        {
            var (type, path) = generationData;

            if (type.Name.Contains(':') || type.Name.Contains('/'))
            {
                logger.LogError($"Ignoring type '{type.Name}' with invalid name.");
                return;
            }

            if (type.ContainingType is not null)
            {
                // Skip nested types, they will be generated as part of the generation of its containing type.
                return;
            }

            using var baseWriter = writerFactory.CreateWriter(path, isTestOutput);
            using var writer = new IndentedTextWriter(baseWriter);

            writer.WriteLine($"namespace {type.Namespace};");
            writer.WriteLine();

            if (!generationData.Nullable)
            {
                writer.WriteLine("#nullable disable");
                writer.WriteLine();
            }

            WriteType(writer, type);
        }
    }

    private static void WriteType(IndentedTextWriter writer, TypeInfo type)
    {
        if (type is DelegateInfo delegateType)
        {
            writer.WriteDocumentation(delegateType);
            writer.WriteAttributes(delegateType);
            writer.WriteDelegateDeclaration(delegateType);
            writer.WriteLine(';');
        }
        else if (type is EnumInfo enumType)
        {
            writer.WriteDocumentation(enumType);
            writer.WriteAttributes(enumType);
            writer.WriteTypeDeclaration(enumType);
            writer.WriteLine();

            writer.OpenBlock();
            foreach (var field in enumType.DeclaredFields)
            {
                // All enum members must be constants.
                Debug.Assert(field.IsLiteral);

                writer.WriteDocumentation(field);
                writer.WriteAttributes(field);
                writer.WriteLine($"{field.Name} = {field.DefaultValue},");
            }
            writer.CloseBlock();
        }
        else
        {
            writer.WriteDocumentation(type);
            writer.WriteAttributes(type);
            writer.WriteTypeDeclaration(type);
            writer.WriteLine();

            writer.OpenBlock();

            foreach (var nestedType in type.NestedTypes)
            {
                WriteType(writer, nestedType);
            }

            foreach (var @event in type.DeclaredEvents)
            {
                writer.WriteDocumentation(@event);
                writer.WriteAttributes(@event);
                writer.WriteEventDeclaration(@event);

                if (@event.AddAccessor is not null && @event.RemoveAccessor is not null)
                {
                    writer.WriteLine();
                    writer.OpenBlock();

                    writer.WriteLine("add");
                    writer.OpenBlock();
                    writer.WriteMethodBody(@event.AddAccessor);
                    writer.CloseBlock();

                    writer.WriteLine("remove");
                    writer.OpenBlock();
                    writer.WriteMethodBody(@event.RemoveAccessor);
                    writer.CloseBlock();

                    writer.CloseBlock();
                }
                else if (@event.AddAccessor is not null || @event.RemoveAccessor is not null)
                {
                    throw new InvalidOperationException($"Event '{@event.Name}' must have both add and remove accessors.");
                }
                else
                {
                    writer.WriteLine(';');
                }
            }

            foreach (var field in type.DeclaredFields)
            {
                writer.WriteDocumentation(field);
                writer.WriteAttributes(field);
                writer.WriteFieldDeclaration(field);
                writer.WriteLine(';');
            }

            foreach (var property in type.DeclaredProperties)
            {
                if (!property.CanRead && !property.CanWrite)
                {
                    throw new InvalidOperationException($"Property '{type.Name}.{property.Name}' must have at least a getter or a setter.");
                }

                writer.WriteDocumentation(property);
                writer.WriteAttributes(property);
                writer.WritePropertyDeclaration(property);
                writer.WriteLine();

                writer.OpenBlock();

                if (property.CanRead)
                {
                    writer.WriteAttributes(property.Getter);
                    if (property.Getter.IsReadOnly)
                    {
                        writer.Write("readonly ");
                    }
                    writer.WriteLine("get");
                    writer.OpenBlock();
                    writer.WriteMethodBody(property.Getter);
                    writer.CloseBlock();
                }

                if (property.CanWrite)
                {
                    writer.WriteAttributes(property.Setter);
                    if (property.Setter.IsReadOnly)
                    {
                        // This is likely a mistake, but we'll do as we are told and write the modifier.
                        writer.Write("readonly ");
                    }
                    writer.WriteLine("set");
                    writer.OpenBlock();
                    writer.WriteMethodBody(property.Setter);
                    writer.CloseBlock();
                }

                writer.CloseBlock();
            }

            foreach (var constructor in type.DeclaredConstructors)
            {
                writer.WriteDocumentation(constructor);
                writer.WriteAttributes(constructor);
                writer.WriteConstructorSignature(constructor, type);
                writer.WriteLine();
                writer.OpenBlock();
                writer.WriteMethodBody(constructor);
                writer.CloseBlock();
            }

            foreach (var method in type.DeclaredMethods)
            {
                Debug.Assert(!method.IsConstructor);

                writer.WriteDocumentation(method);
                writer.WriteAttributes(method);
                if (method.ReturnParameter is not null)
                {
                    Debug.Assert(method.ReturnParameter.Attributes.All(attr => attr.StartsWith("[return:", StringComparison.Ordinal)), $"Method '{method.Name}' has return attributes with the wrong target.");
                    writer.WriteAttributes(method.ReturnParameter);
                }
                writer.WriteMethodSignature(method);
                if (method.IsAbstract)
                {
                    writer.WriteLine(';');
                }
                else
                {
                    writer.WriteLine();
                    writer.OpenBlock();
                    writer.WriteMethodBody(method);
                    writer.CloseBlock();
                }
            }

            writer.CloseBlock();
        }
    }
}
